import {DataTypes, Sequelize} from 'sequelize'

// TODO:: Autogenerated id
const User = (sequelize: Sequelize) =>
    sequelize.define('User', {
        id: {type: DataTypes.INTEGER, primaryKey: true, autoIncrement: true},
        names: {type: DataTypes.STRING},
        surnames: {type: DataTypes.STRING},
        email: {type: DataTypes.STRING},
        password: {type: DataTypes.STRING}
    })

// TODO:: Autogenerated id
const Board = (sequelize: Sequelize) =>
    sequelize.define('Board', {
        id: {type: DataTypes.INTEGER, primaryKey: true, autoIncrement: true},
        name: {type: DataTypes.STRING}
    })

export const initializeModel = async (sequelize: Sequelize) => ({
    User: User(sequelize),
    Board: Board(sequelize)
})
