# TODO - Add proper ENV VAR configuration and CircleCI to some README.
version: 2.1

orbs:
  aws-ecr: circleci/aws-ecr@8.1.3
  aws-ecs: circleci/aws-ecs@3.2.0
workflows:
  build_and_push_image:
    jobs:
      - aws-ecr/build-and-push-image:
          path: ./packages/backend
          repo: 'my-first-ecr-repo'
      - aws-ecs/deploy-service-update:
          cluster: 'my-cluster'
          family: 'my-first-task'
          service-name: 'my-first-service'
          requires:
            - aws-ecr/build-and-push-image
