version: 2.1
orbs:
  node: circleci/node@5.0.3
jobs:
  install-and-test:
    executor: node/default
    steps:
      - checkout
      - node/install-packages:
          pkg-manager: yarn
      - run: yarn
      - run: yarn test
      - run: yarn build
workflows:
  install-and-test:
    jobs:
      - install-and-test
