version: 2.1
orbs:
  node: circleci/node@5.0.3
  aws-s3: circleci/aws-s3@3.1.1
  aws-cli: circleci/aws-cli@3.1
  aws-ecr: circleci/aws-ecr@8.1.3
  aws-ecs: circleci/aws-ecs@3.2.0
jobs:
  install-test-and-build:
    executor: node/default
    steps:
      - checkout
      - node/install-packages:
          pkg-manager: yarn
      - run: yarn
      - run: yarn test
      - run: yarn build
      - run: yarn build:webpack
      - persist_to_workspace:
          root: .
          paths:
           - .
  frontend-deploy:
    executor: node/default
    steps:
      - attach_workspace:
          at: .
      - aws-s3/sync:
          from: ./packages/frontend/build
          to: 's3://trello-clone-frontend'
          aws-access-key-id: AWS_ACCESS_KEY_ID
          aws-region: AWS_REGION
          aws-secret-access-key: AWS_SECRET_ACCESS_KEY
  backend-deploy-serverless:
    executor: aws-cli/default
    steps:
      - attach_workspace:
          at: .
      - aws-cli/setup:
          profile-name: default
      - run: aws lambda update-function-code --function-name trello-clone-backend-lambda --zip-file fileb://packages/backend/build-webpack/lambda.zip

workflows:
  full-stack-build-test-and-deploy:
    jobs:
      - install-test-and-build
      - frontend-deploy:
          requires:
            - install-test-and-build
          filters:
            branches:
              only: main
#      - backend-deploy-serverless
#      - aws-ecr/build-and-push-image:
#          path: ./packages/backend
#          repo: 'trello-clone-ecr-repo'
#          requires:
#            - install-test-and-build
#          filters:
#            branches:
#              only: main
#      - aws-ecs/deploy-service-update:
#          cluster: 'trello-clone-ecs-cluster'
#          family: 'trello-clone-ecs-task'
#          service-name: 'trello-clone-ecs-service'
#          requires:
#            - install-test-and-build
#            - aws-ecr/build-and-push-image
#          filters:
#            branches:
#              only: main
