version: 2.1

orbs:
  aws-ecr: circleci/aws-ecr@8.1.3
  aws-ecs: circleci/aws-ecs@3.2.0
workflows:
  build_and_push_image:
    jobs:
      - aws-ecr/build-and-push-image:
          path: ./packages/backend
          repo: 'aws-monorepo-ecr-repo'
      - aws-ecs/deploy-service-update:
          cluster: 'aws-monorepo-ecs-cluster'
          family: 'aws-monorepo-ecs-task'
          service-name: 'aws-monorepo-ecs-service'
          requires:
            - aws-ecr/build-and-push-image
