version: '3'
services:
  aws-monorepo-backend:
    build: .
    depends_on:
      - postgres
    links:
      - postgres
    ports:
      - 4000:4000
    env_file:
      - .env.docker
    restart: on-failure
  postgres:
    image: postgres:15.1-alpine
    ports:
      - 5432:5432
    environment:
      - POSTGRES_DB=db
      - POSTGRES_USER=user
      - POSTGRES_PASSWORD=password
