version: '3'
services:
  trello-clone-backend:
    build: .
    depends_on:
      - postgres
    links:
      - postgres
    ports:
      - 4000:4000
    env_file:
      - .env.docker
    restart: on-failure
